### ISSUE TITLE
Failed to connect to Tika server while indexing

### ISSUE THREAD

**Issue by YoannMR** [opensemanticsearch/open-semantic-search#114]
Hi,

I restarted my instance open semantic search server and it doesn't seem to be able to index anymore.

I'm getting the error message below:

Exception while data enrichment of /folder/file.html with plugin enhance_extract_text_tika_server: (7, 'Failed to connect to localhost port 9998: Connection refused')

I tried restarting solr but it didn't help.

Any idea what may be causing this?
Thanks,
Yoann

**Comment by opensemanticsearch** [comment]
If you did an update which upgraded the tika-server.jar to newer version, you must do an reboot (or kill tika-server daemon, remove the pid file and start it again) until https://github.com/opensemanticsearch/tika-server.deb/issues/2 is solved.

Please reopen if not running after reboot.

**Comment by YoannMR** [comment]
Thanks for your answer!

I don't see a tika-server daemon running. I tried 
service tika stop
service tika restart

But that didn't fix it.
I tried re-starting the instance which didn't work either.
I have not updated open semantic search. Would an ubuntu update impact it?

**Comment by YoannMR** [comment]
I found a way to restart it manually going to:

/usr/share/java

then manually starting tika

exec java -jar tika-server-1.15.jar

Is there a place I should check to make it automatic again?

**Comment by opensemanticsearch** [comment]
Newer releases of Open Semantic ETL wait for Tika start so no such Tika errors while indexing anymore: https://github.com/opensemanticsearch/open-semantic-etl/issues/84.

Automatic upgrades without manual killing after https://github.com/opensemanticsearch/tika-server.deb/issues/2 solved.
